// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"datacatAgent/ent/categorymain"
	"datacatAgent/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CategoryMainQuery is the builder for querying CategoryMain entities.
type CategoryMainQuery struct {
	config
	ctx        *QueryContext
	order      []categorymain.OrderOption
	inters     []Interceptor
	predicates []predicate.CategoryMain
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CategoryMainQuery builder.
func (cmq *CategoryMainQuery) Where(ps ...predicate.CategoryMain) *CategoryMainQuery {
	cmq.predicates = append(cmq.predicates, ps...)
	return cmq
}

// Limit the number of records to be returned by this query.
func (cmq *CategoryMainQuery) Limit(limit int) *CategoryMainQuery {
	cmq.ctx.Limit = &limit
	return cmq
}

// Offset to start from.
func (cmq *CategoryMainQuery) Offset(offset int) *CategoryMainQuery {
	cmq.ctx.Offset = &offset
	return cmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cmq *CategoryMainQuery) Unique(unique bool) *CategoryMainQuery {
	cmq.ctx.Unique = &unique
	return cmq
}

// Order specifies how the records should be ordered.
func (cmq *CategoryMainQuery) Order(o ...categorymain.OrderOption) *CategoryMainQuery {
	cmq.order = append(cmq.order, o...)
	return cmq
}

// First returns the first CategoryMain entity from the query.
// Returns a *NotFoundError when no CategoryMain was found.
func (cmq *CategoryMainQuery) First(ctx context.Context) (*CategoryMain, error) {
	nodes, err := cmq.Limit(1).All(setContextOp(ctx, cmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{categorymain.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cmq *CategoryMainQuery) FirstX(ctx context.Context) *CategoryMain {
	node, err := cmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CategoryMain ID from the query.
// Returns a *NotFoundError when no CategoryMain ID was found.
func (cmq *CategoryMainQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = cmq.Limit(1).IDs(setContextOp(ctx, cmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{categorymain.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cmq *CategoryMainQuery) FirstIDX(ctx context.Context) int32 {
	id, err := cmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CategoryMain entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CategoryMain entity is found.
// Returns a *NotFoundError when no CategoryMain entities are found.
func (cmq *CategoryMainQuery) Only(ctx context.Context) (*CategoryMain, error) {
	nodes, err := cmq.Limit(2).All(setContextOp(ctx, cmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{categorymain.Label}
	default:
		return nil, &NotSingularError{categorymain.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cmq *CategoryMainQuery) OnlyX(ctx context.Context) *CategoryMain {
	node, err := cmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CategoryMain ID in the query.
// Returns a *NotSingularError when more than one CategoryMain ID is found.
// Returns a *NotFoundError when no entities are found.
func (cmq *CategoryMainQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = cmq.Limit(2).IDs(setContextOp(ctx, cmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{categorymain.Label}
	default:
		err = &NotSingularError{categorymain.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cmq *CategoryMainQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := cmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CategoryMains.
func (cmq *CategoryMainQuery) All(ctx context.Context) ([]*CategoryMain, error) {
	ctx = setContextOp(ctx, cmq.ctx, "All")
	if err := cmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CategoryMain, *CategoryMainQuery]()
	return withInterceptors[[]*CategoryMain](ctx, cmq, qr, cmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cmq *CategoryMainQuery) AllX(ctx context.Context) []*CategoryMain {
	nodes, err := cmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CategoryMain IDs.
func (cmq *CategoryMainQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if cmq.ctx.Unique == nil && cmq.path != nil {
		cmq.Unique(true)
	}
	ctx = setContextOp(ctx, cmq.ctx, "IDs")
	if err = cmq.Select(categorymain.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cmq *CategoryMainQuery) IDsX(ctx context.Context) []int32 {
	ids, err := cmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cmq *CategoryMainQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cmq.ctx, "Count")
	if err := cmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cmq, querierCount[*CategoryMainQuery](), cmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cmq *CategoryMainQuery) CountX(ctx context.Context) int {
	count, err := cmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cmq *CategoryMainQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cmq.ctx, "Exist")
	switch _, err := cmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cmq *CategoryMainQuery) ExistX(ctx context.Context) bool {
	exist, err := cmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CategoryMainQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cmq *CategoryMainQuery) Clone() *CategoryMainQuery {
	if cmq == nil {
		return nil
	}
	return &CategoryMainQuery{
		config:     cmq.config,
		ctx:        cmq.ctx.Clone(),
		order:      append([]categorymain.OrderOption{}, cmq.order...),
		inters:     append([]Interceptor{}, cmq.inters...),
		predicates: append([]predicate.CategoryMain{}, cmq.predicates...),
		// clone intermediate query.
		sql:  cmq.sql.Clone(),
		path: cmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Program string `json:"program,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CategoryMain.Query().
//		GroupBy(categorymain.FieldProgram).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cmq *CategoryMainQuery) GroupBy(field string, fields ...string) *CategoryMainGroupBy {
	cmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CategoryMainGroupBy{build: cmq}
	grbuild.flds = &cmq.ctx.Fields
	grbuild.label = categorymain.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Program string `json:"program,omitempty"`
//	}
//
//	client.CategoryMain.Query().
//		Select(categorymain.FieldProgram).
//		Scan(ctx, &v)
func (cmq *CategoryMainQuery) Select(fields ...string) *CategoryMainSelect {
	cmq.ctx.Fields = append(cmq.ctx.Fields, fields...)
	sbuild := &CategoryMainSelect{CategoryMainQuery: cmq}
	sbuild.label = categorymain.Label
	sbuild.flds, sbuild.scan = &cmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CategoryMainSelect configured with the given aggregations.
func (cmq *CategoryMainQuery) Aggregate(fns ...AggregateFunc) *CategoryMainSelect {
	return cmq.Select().Aggregate(fns...)
}

func (cmq *CategoryMainQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cmq); err != nil {
				return err
			}
		}
	}
	for _, f := range cmq.ctx.Fields {
		if !categorymain.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cmq.path != nil {
		prev, err := cmq.path(ctx)
		if err != nil {
			return err
		}
		cmq.sql = prev
	}
	return nil
}

func (cmq *CategoryMainQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CategoryMain, error) {
	var (
		nodes = []*CategoryMain{}
		_spec = cmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CategoryMain).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CategoryMain{config: cmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cmq *CategoryMainQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cmq.querySpec()
	_spec.Node.Columns = cmq.ctx.Fields
	if len(cmq.ctx.Fields) > 0 {
		_spec.Unique = cmq.ctx.Unique != nil && *cmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cmq.driver, _spec)
}

func (cmq *CategoryMainQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(categorymain.Table, categorymain.Columns, sqlgraph.NewFieldSpec(categorymain.FieldID, field.TypeInt32))
	_spec.From = cmq.sql
	if unique := cmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cmq.path != nil {
		_spec.Unique = true
	}
	if fields := cmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, categorymain.FieldID)
		for i := range fields {
			if fields[i] != categorymain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cmq *CategoryMainQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cmq.driver.Dialect())
	t1 := builder.Table(categorymain.Table)
	columns := cmq.ctx.Fields
	if len(columns) == 0 {
		columns = categorymain.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cmq.sql != nil {
		selector = cmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cmq.ctx.Unique != nil && *cmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cmq.predicates {
		p(selector)
	}
	for _, p := range cmq.order {
		p(selector)
	}
	if offset := cmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CategoryMainGroupBy is the group-by builder for CategoryMain entities.
type CategoryMainGroupBy struct {
	selector
	build *CategoryMainQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cmgb *CategoryMainGroupBy) Aggregate(fns ...AggregateFunc) *CategoryMainGroupBy {
	cmgb.fns = append(cmgb.fns, fns...)
	return cmgb
}

// Scan applies the selector query and scans the result into the given value.
func (cmgb *CategoryMainGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cmgb.build.ctx, "GroupBy")
	if err := cmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CategoryMainQuery, *CategoryMainGroupBy](ctx, cmgb.build, cmgb, cmgb.build.inters, v)
}

func (cmgb *CategoryMainGroupBy) sqlScan(ctx context.Context, root *CategoryMainQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cmgb.fns))
	for _, fn := range cmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cmgb.flds)+len(cmgb.fns))
		for _, f := range *cmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CategoryMainSelect is the builder for selecting fields of CategoryMain entities.
type CategoryMainSelect struct {
	*CategoryMainQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cms *CategoryMainSelect) Aggregate(fns ...AggregateFunc) *CategoryMainSelect {
	cms.fns = append(cms.fns, fns...)
	return cms
}

// Scan applies the selector query and scans the result into the given value.
func (cms *CategoryMainSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cms.ctx, "Select")
	if err := cms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CategoryMainQuery, *CategoryMainSelect](ctx, cms.CategoryMainQuery, cms, cms.inters, v)
}

func (cms *CategoryMainSelect) sqlScan(ctx context.Context, root *CategoryMainQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cms.fns))
	for _, fn := range cms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
