// Code generated by ent, DO NOT EDIT.

package ent

import (
	"datacatAgent/ent/categorysub"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CategorySub is the model entity for the CategorySub schema.
type CategorySub struct {
	config `json:"-"`
	// ID of the ent.
	ID int32 `json:"id,omitempty"`
	// Program holds the value of the "program" field.
	Program string `json:"program,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// UpdatedById holds the value of the "updatedById" field.
	UpdatedById int `json:"updatedById,omitempty"`
	// CreatedById holds the value of the "createdById" field.
	CreatedById int `json:"createdById,omitempty"`
	// CategoryMainId holds the value of the "categoryMainId" field.
	CategoryMainId int32 `json:"categoryMainId,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CategorySub) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case categorysub.FieldID, categorysub.FieldUpdatedById, categorysub.FieldCreatedById, categorysub.FieldCategoryMainId:
			values[i] = new(sql.NullInt64)
		case categorysub.FieldProgram, categorysub.FieldName:
			values[i] = new(sql.NullString)
		case categorysub.FieldUpdatedAt, categorysub.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CategorySub fields.
func (cs *CategorySub) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case categorysub.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cs.ID = int32(value.Int64)
		case categorysub.FieldProgram:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field program", values[i])
			} else if value.Valid {
				cs.Program = value.String
			}
		case categorysub.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				cs.UpdatedAt = value.Time
			}
		case categorysub.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				cs.CreatedAt = value.Time
			}
		case categorysub.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				cs.Name = value.String
			}
		case categorysub.FieldUpdatedById:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updatedById", values[i])
			} else if value.Valid {
				cs.UpdatedById = int(value.Int64)
			}
		case categorysub.FieldCreatedById:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field createdById", values[i])
			} else if value.Valid {
				cs.CreatedById = int(value.Int64)
			}
		case categorysub.FieldCategoryMainId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field categoryMainId", values[i])
			} else if value.Valid {
				cs.CategoryMainId = int32(value.Int64)
			}
		default:
			cs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CategorySub.
// This includes values selected through modifiers, order, etc.
func (cs *CategorySub) Value(name string) (ent.Value, error) {
	return cs.selectValues.Get(name)
}

// Update returns a builder for updating this CategorySub.
// Note that you need to call CategorySub.Unwrap() before calling this method if this CategorySub
// was returned from a transaction, and the transaction was committed or rolled back.
func (cs *CategorySub) Update() *CategorySubUpdateOne {
	return NewCategorySubClient(cs.config).UpdateOne(cs)
}

// Unwrap unwraps the CategorySub entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cs *CategorySub) Unwrap() *CategorySub {
	_tx, ok := cs.config.driver.(*txDriver)
	if !ok {
		panic("ent: CategorySub is not a transactional entity")
	}
	cs.config.driver = _tx.drv
	return cs
}

// String implements the fmt.Stringer.
func (cs *CategorySub) String() string {
	var builder strings.Builder
	builder.WriteString("CategorySub(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cs.ID))
	builder.WriteString("program=")
	builder.WriteString(cs.Program)
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(cs.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(cs.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(cs.Name)
	builder.WriteString(", ")
	builder.WriteString("updatedById=")
	builder.WriteString(fmt.Sprintf("%v", cs.UpdatedById))
	builder.WriteString(", ")
	builder.WriteString("createdById=")
	builder.WriteString(fmt.Sprintf("%v", cs.CreatedById))
	builder.WriteString(", ")
	builder.WriteString("categoryMainId=")
	builder.WriteString(fmt.Sprintf("%v", cs.CategoryMainId))
	builder.WriteByte(')')
	return builder.String()
}

// CategorySubs is a parsable slice of CategorySub.
type CategorySubs []*CategorySub
