// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"datacatAgent/ent/job"
	"datacatAgent/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (ju *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	ju.mutation.Where(ps...)
	return ju
}

// SetProgram sets the "program" field.
func (ju *JobUpdate) SetProgram(s string) *JobUpdate {
	ju.mutation.SetProgram(s)
	return ju
}

// SetNillableProgram sets the "program" field if the given value is not nil.
func (ju *JobUpdate) SetNillableProgram(s *string) *JobUpdate {
	if s != nil {
		ju.SetProgram(*s)
	}
	return ju
}

// SetUpdatedAt sets the "updatedAt" field.
func (ju *JobUpdate) SetUpdatedAt(t time.Time) *JobUpdate {
	ju.mutation.SetUpdatedAt(t)
	return ju
}

// SetName sets the "name" field.
func (ju *JobUpdate) SetName(s string) *JobUpdate {
	ju.mutation.SetName(s)
	return ju
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ju *JobUpdate) SetNillableName(s *string) *JobUpdate {
	if s != nil {
		ju.SetName(*s)
	}
	return ju
}

// SetUpdatedById sets the "updatedById" field.
func (ju *JobUpdate) SetUpdatedById(i int) *JobUpdate {
	ju.mutation.ResetUpdatedById()
	ju.mutation.SetUpdatedById(i)
	return ju
}

// SetNillableUpdatedById sets the "updatedById" field if the given value is not nil.
func (ju *JobUpdate) SetNillableUpdatedById(i *int) *JobUpdate {
	if i != nil {
		ju.SetUpdatedById(*i)
	}
	return ju
}

// AddUpdatedById adds i to the "updatedById" field.
func (ju *JobUpdate) AddUpdatedById(i int) *JobUpdate {
	ju.mutation.AddUpdatedById(i)
	return ju
}

// SetCreatedById sets the "createdById" field.
func (ju *JobUpdate) SetCreatedById(i int) *JobUpdate {
	ju.mutation.ResetCreatedById()
	ju.mutation.SetCreatedById(i)
	return ju
}

// SetNillableCreatedById sets the "createdById" field if the given value is not nil.
func (ju *JobUpdate) SetNillableCreatedById(i *int) *JobUpdate {
	if i != nil {
		ju.SetCreatedById(*i)
	}
	return ju
}

// AddCreatedById adds i to the "createdById" field.
func (ju *JobUpdate) AddCreatedById(i int) *JobUpdate {
	ju.mutation.AddCreatedById(i)
	return ju
}

// SetCategorySubId sets the "categorySubId" field.
func (ju *JobUpdate) SetCategorySubId(i int) *JobUpdate {
	ju.mutation.ResetCategorySubId()
	ju.mutation.SetCategorySubId(i)
	return ju
}

// SetNillableCategorySubId sets the "categorySubId" field if the given value is not nil.
func (ju *JobUpdate) SetNillableCategorySubId(i *int) *JobUpdate {
	if i != nil {
		ju.SetCategorySubId(*i)
	}
	return ju
}

// AddCategorySubId adds i to the "categorySubId" field.
func (ju *JobUpdate) AddCategorySubId(i int) *JobUpdate {
	ju.mutation.AddCategorySubId(i)
	return ju
}

// Mutation returns the JobMutation object of the builder.
func (ju *JobUpdate) Mutation() *JobMutation {
	return ju.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ju *JobUpdate) Save(ctx context.Context) (int, error) {
	ju.defaults()
	return withHooks(ctx, ju.sqlSave, ju.mutation, ju.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ju *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := ju.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ju *JobUpdate) Exec(ctx context.Context) error {
	_, err := ju.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ju *JobUpdate) ExecX(ctx context.Context) {
	if err := ju.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ju *JobUpdate) defaults() {
	if _, ok := ju.mutation.UpdatedAt(); !ok {
		v := job.UpdateDefaultUpdatedAt()
		ju.mutation.SetUpdatedAt(v)
	}
}

func (ju *JobUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt32))
	if ps := ju.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ju.mutation.Program(); ok {
		_spec.SetField(job.FieldProgram, field.TypeString, value)
	}
	if value, ok := ju.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ju.mutation.Name(); ok {
		_spec.SetField(job.FieldName, field.TypeString, value)
	}
	if value, ok := ju.mutation.UpdatedById(); ok {
		_spec.SetField(job.FieldUpdatedById, field.TypeInt, value)
	}
	if value, ok := ju.mutation.AddedUpdatedById(); ok {
		_spec.AddField(job.FieldUpdatedById, field.TypeInt, value)
	}
	if value, ok := ju.mutation.CreatedById(); ok {
		_spec.SetField(job.FieldCreatedById, field.TypeInt, value)
	}
	if value, ok := ju.mutation.AddedCreatedById(); ok {
		_spec.AddField(job.FieldCreatedById, field.TypeInt, value)
	}
	if value, ok := ju.mutation.CategorySubId(); ok {
		_spec.SetField(job.FieldCategorySubId, field.TypeInt, value)
	}
	if value, ok := ju.mutation.AddedCategorySubId(); ok {
		_spec.AddField(job.FieldCategorySubId, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ju.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ju.mutation.done = true
	return n, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetProgram sets the "program" field.
func (juo *JobUpdateOne) SetProgram(s string) *JobUpdateOne {
	juo.mutation.SetProgram(s)
	return juo
}

// SetNillableProgram sets the "program" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableProgram(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetProgram(*s)
	}
	return juo
}

// SetUpdatedAt sets the "updatedAt" field.
func (juo *JobUpdateOne) SetUpdatedAt(t time.Time) *JobUpdateOne {
	juo.mutation.SetUpdatedAt(t)
	return juo
}

// SetName sets the "name" field.
func (juo *JobUpdateOne) SetName(s string) *JobUpdateOne {
	juo.mutation.SetName(s)
	return juo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableName(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetName(*s)
	}
	return juo
}

// SetUpdatedById sets the "updatedById" field.
func (juo *JobUpdateOne) SetUpdatedById(i int) *JobUpdateOne {
	juo.mutation.ResetUpdatedById()
	juo.mutation.SetUpdatedById(i)
	return juo
}

// SetNillableUpdatedById sets the "updatedById" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableUpdatedById(i *int) *JobUpdateOne {
	if i != nil {
		juo.SetUpdatedById(*i)
	}
	return juo
}

// AddUpdatedById adds i to the "updatedById" field.
func (juo *JobUpdateOne) AddUpdatedById(i int) *JobUpdateOne {
	juo.mutation.AddUpdatedById(i)
	return juo
}

// SetCreatedById sets the "createdById" field.
func (juo *JobUpdateOne) SetCreatedById(i int) *JobUpdateOne {
	juo.mutation.ResetCreatedById()
	juo.mutation.SetCreatedById(i)
	return juo
}

// SetNillableCreatedById sets the "createdById" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableCreatedById(i *int) *JobUpdateOne {
	if i != nil {
		juo.SetCreatedById(*i)
	}
	return juo
}

// AddCreatedById adds i to the "createdById" field.
func (juo *JobUpdateOne) AddCreatedById(i int) *JobUpdateOne {
	juo.mutation.AddCreatedById(i)
	return juo
}

// SetCategorySubId sets the "categorySubId" field.
func (juo *JobUpdateOne) SetCategorySubId(i int) *JobUpdateOne {
	juo.mutation.ResetCategorySubId()
	juo.mutation.SetCategorySubId(i)
	return juo
}

// SetNillableCategorySubId sets the "categorySubId" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableCategorySubId(i *int) *JobUpdateOne {
	if i != nil {
		juo.SetCategorySubId(*i)
	}
	return juo
}

// AddCategorySubId adds i to the "categorySubId" field.
func (juo *JobUpdateOne) AddCategorySubId(i int) *JobUpdateOne {
	juo.mutation.AddCategorySubId(i)
	return juo
}

// Mutation returns the JobMutation object of the builder.
func (juo *JobUpdateOne) Mutation() *JobMutation {
	return juo.mutation
}

// Where appends a list predicates to the JobUpdate builder.
func (juo *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	juo.mutation.Where(ps...)
	return juo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (juo *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	juo.fields = append([]string{field}, fields...)
	return juo
}

// Save executes the query and returns the updated Job entity.
func (juo *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	juo.defaults()
	return withHooks(ctx, juo.sqlSave, juo.mutation, juo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (juo *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := juo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (juo *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := juo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (juo *JobUpdateOne) ExecX(ctx context.Context) {
	if err := juo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (juo *JobUpdateOne) defaults() {
	if _, ok := juo.mutation.UpdatedAt(); !ok {
		v := job.UpdateDefaultUpdatedAt()
		juo.mutation.SetUpdatedAt(v)
	}
}

func (juo *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt32))
	id, ok := juo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := juo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := juo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := juo.mutation.Program(); ok {
		_spec.SetField(job.FieldProgram, field.TypeString, value)
	}
	if value, ok := juo.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := juo.mutation.Name(); ok {
		_spec.SetField(job.FieldName, field.TypeString, value)
	}
	if value, ok := juo.mutation.UpdatedById(); ok {
		_spec.SetField(job.FieldUpdatedById, field.TypeInt, value)
	}
	if value, ok := juo.mutation.AddedUpdatedById(); ok {
		_spec.AddField(job.FieldUpdatedById, field.TypeInt, value)
	}
	if value, ok := juo.mutation.CreatedById(); ok {
		_spec.SetField(job.FieldCreatedById, field.TypeInt, value)
	}
	if value, ok := juo.mutation.AddedCreatedById(); ok {
		_spec.AddField(job.FieldCreatedById, field.TypeInt, value)
	}
	if value, ok := juo.mutation.CategorySubId(); ok {
		_spec.SetField(job.FieldCategorySubId, field.TypeInt, value)
	}
	if value, ok := juo.mutation.AddedCategorySubId(); ok {
		_spec.AddField(job.FieldCategorySubId, field.TypeInt, value)
	}
	_node = &Job{config: juo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, juo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	juo.mutation.done = true
	return _node, nil
}
