// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"datacatAgent/ent/messagemail"
	"datacatAgent/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessageMailDelete is the builder for deleting a MessageMail entity.
type MessageMailDelete struct {
	config
	hooks    []Hook
	mutation *MessageMailMutation
}

// Where appends a list predicates to the MessageMailDelete builder.
func (mmd *MessageMailDelete) Where(ps ...predicate.MessageMail) *MessageMailDelete {
	mmd.mutation.Where(ps...)
	return mmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mmd *MessageMailDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mmd.sqlExec, mmd.mutation, mmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mmd *MessageMailDelete) ExecX(ctx context.Context) int {
	n, err := mmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mmd *MessageMailDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(messagemail.Table, sqlgraph.NewFieldSpec(messagemail.FieldID, field.TypeInt))
	if ps := mmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mmd.mutation.done = true
	return affected, err
}

// MessageMailDeleteOne is the builder for deleting a single MessageMail entity.
type MessageMailDeleteOne struct {
	mmd *MessageMailDelete
}

// Where appends a list predicates to the MessageMailDelete builder.
func (mmdo *MessageMailDeleteOne) Where(ps ...predicate.MessageMail) *MessageMailDeleteOne {
	mmdo.mmd.mutation.Where(ps...)
	return mmdo
}

// Exec executes the deletion query.
func (mmdo *MessageMailDeleteOne) Exec(ctx context.Context) error {
	n, err := mmdo.mmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{messagemail.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mmdo *MessageMailDeleteOne) ExecX(ctx context.Context) {
	if err := mmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
