// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"datacatAgent/ent/messagemail"
	"datacatAgent/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessageMailQuery is the builder for querying MessageMail entities.
type MessageMailQuery struct {
	config
	ctx        *QueryContext
	order      []messagemail.OrderOption
	inters     []Interceptor
	predicates []predicate.MessageMail
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MessageMailQuery builder.
func (mmq *MessageMailQuery) Where(ps ...predicate.MessageMail) *MessageMailQuery {
	mmq.predicates = append(mmq.predicates, ps...)
	return mmq
}

// Limit the number of records to be returned by this query.
func (mmq *MessageMailQuery) Limit(limit int) *MessageMailQuery {
	mmq.ctx.Limit = &limit
	return mmq
}

// Offset to start from.
func (mmq *MessageMailQuery) Offset(offset int) *MessageMailQuery {
	mmq.ctx.Offset = &offset
	return mmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mmq *MessageMailQuery) Unique(unique bool) *MessageMailQuery {
	mmq.ctx.Unique = &unique
	return mmq
}

// Order specifies how the records should be ordered.
func (mmq *MessageMailQuery) Order(o ...messagemail.OrderOption) *MessageMailQuery {
	mmq.order = append(mmq.order, o...)
	return mmq
}

// First returns the first MessageMail entity from the query.
// Returns a *NotFoundError when no MessageMail was found.
func (mmq *MessageMailQuery) First(ctx context.Context) (*MessageMail, error) {
	nodes, err := mmq.Limit(1).All(setContextOp(ctx, mmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{messagemail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mmq *MessageMailQuery) FirstX(ctx context.Context) *MessageMail {
	node, err := mmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MessageMail ID from the query.
// Returns a *NotFoundError when no MessageMail ID was found.
func (mmq *MessageMailQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mmq.Limit(1).IDs(setContextOp(ctx, mmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{messagemail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mmq *MessageMailQuery) FirstIDX(ctx context.Context) int {
	id, err := mmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MessageMail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MessageMail entity is found.
// Returns a *NotFoundError when no MessageMail entities are found.
func (mmq *MessageMailQuery) Only(ctx context.Context) (*MessageMail, error) {
	nodes, err := mmq.Limit(2).All(setContextOp(ctx, mmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{messagemail.Label}
	default:
		return nil, &NotSingularError{messagemail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mmq *MessageMailQuery) OnlyX(ctx context.Context) *MessageMail {
	node, err := mmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MessageMail ID in the query.
// Returns a *NotSingularError when more than one MessageMail ID is found.
// Returns a *NotFoundError when no entities are found.
func (mmq *MessageMailQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mmq.Limit(2).IDs(setContextOp(ctx, mmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{messagemail.Label}
	default:
		err = &NotSingularError{messagemail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mmq *MessageMailQuery) OnlyIDX(ctx context.Context) int {
	id, err := mmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MessageMails.
func (mmq *MessageMailQuery) All(ctx context.Context) ([]*MessageMail, error) {
	ctx = setContextOp(ctx, mmq.ctx, "All")
	if err := mmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MessageMail, *MessageMailQuery]()
	return withInterceptors[[]*MessageMail](ctx, mmq, qr, mmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mmq *MessageMailQuery) AllX(ctx context.Context) []*MessageMail {
	nodes, err := mmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MessageMail IDs.
func (mmq *MessageMailQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mmq.ctx.Unique == nil && mmq.path != nil {
		mmq.Unique(true)
	}
	ctx = setContextOp(ctx, mmq.ctx, "IDs")
	if err = mmq.Select(messagemail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mmq *MessageMailQuery) IDsX(ctx context.Context) []int {
	ids, err := mmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mmq *MessageMailQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mmq.ctx, "Count")
	if err := mmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mmq, querierCount[*MessageMailQuery](), mmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mmq *MessageMailQuery) CountX(ctx context.Context) int {
	count, err := mmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mmq *MessageMailQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mmq.ctx, "Exist")
	switch _, err := mmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mmq *MessageMailQuery) ExistX(ctx context.Context) bool {
	exist, err := mmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MessageMailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mmq *MessageMailQuery) Clone() *MessageMailQuery {
	if mmq == nil {
		return nil
	}
	return &MessageMailQuery{
		config:     mmq.config,
		ctx:        mmq.ctx.Clone(),
		order:      append([]messagemail.OrderOption{}, mmq.order...),
		inters:     append([]Interceptor{}, mmq.inters...),
		predicates: append([]predicate.MessageMail{}, mmq.predicates...),
		// clone intermediate query.
		sql:  mmq.sql.Clone(),
		path: mmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Seq int64 `json:"seq,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MessageMail.Query().
//		GroupBy(messagemail.FieldSeq).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mmq *MessageMailQuery) GroupBy(field string, fields ...string) *MessageMailGroupBy {
	mmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MessageMailGroupBy{build: mmq}
	grbuild.flds = &mmq.ctx.Fields
	grbuild.label = messagemail.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Seq int64 `json:"seq,omitempty"`
//	}
//
//	client.MessageMail.Query().
//		Select(messagemail.FieldSeq).
//		Scan(ctx, &v)
func (mmq *MessageMailQuery) Select(fields ...string) *MessageMailSelect {
	mmq.ctx.Fields = append(mmq.ctx.Fields, fields...)
	sbuild := &MessageMailSelect{MessageMailQuery: mmq}
	sbuild.label = messagemail.Label
	sbuild.flds, sbuild.scan = &mmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MessageMailSelect configured with the given aggregations.
func (mmq *MessageMailQuery) Aggregate(fns ...AggregateFunc) *MessageMailSelect {
	return mmq.Select().Aggregate(fns...)
}

func (mmq *MessageMailQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mmq); err != nil {
				return err
			}
		}
	}
	for _, f := range mmq.ctx.Fields {
		if !messagemail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mmq.path != nil {
		prev, err := mmq.path(ctx)
		if err != nil {
			return err
		}
		mmq.sql = prev
	}
	return nil
}

func (mmq *MessageMailQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MessageMail, error) {
	var (
		nodes = []*MessageMail{}
		_spec = mmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MessageMail).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MessageMail{config: mmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mmq *MessageMailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mmq.querySpec()
	_spec.Node.Columns = mmq.ctx.Fields
	if len(mmq.ctx.Fields) > 0 {
		_spec.Unique = mmq.ctx.Unique != nil && *mmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mmq.driver, _spec)
}

func (mmq *MessageMailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(messagemail.Table, messagemail.Columns, sqlgraph.NewFieldSpec(messagemail.FieldID, field.TypeInt))
	_spec.From = mmq.sql
	if unique := mmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mmq.path != nil {
		_spec.Unique = true
	}
	if fields := mmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messagemail.FieldID)
		for i := range fields {
			if fields[i] != messagemail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mmq *MessageMailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mmq.driver.Dialect())
	t1 := builder.Table(messagemail.Table)
	columns := mmq.ctx.Fields
	if len(columns) == 0 {
		columns = messagemail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mmq.sql != nil {
		selector = mmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mmq.ctx.Unique != nil && *mmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mmq.predicates {
		p(selector)
	}
	for _, p := range mmq.order {
		p(selector)
	}
	if offset := mmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MessageMailGroupBy is the group-by builder for MessageMail entities.
type MessageMailGroupBy struct {
	selector
	build *MessageMailQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mmgb *MessageMailGroupBy) Aggregate(fns ...AggregateFunc) *MessageMailGroupBy {
	mmgb.fns = append(mmgb.fns, fns...)
	return mmgb
}

// Scan applies the selector query and scans the result into the given value.
func (mmgb *MessageMailGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mmgb.build.ctx, "GroupBy")
	if err := mmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MessageMailQuery, *MessageMailGroupBy](ctx, mmgb.build, mmgb, mmgb.build.inters, v)
}

func (mmgb *MessageMailGroupBy) sqlScan(ctx context.Context, root *MessageMailQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mmgb.fns))
	for _, fn := range mmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mmgb.flds)+len(mmgb.fns))
		for _, f := range *mmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MessageMailSelect is the builder for selecting fields of MessageMail entities.
type MessageMailSelect struct {
	*MessageMailQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mms *MessageMailSelect) Aggregate(fns ...AggregateFunc) *MessageMailSelect {
	mms.fns = append(mms.fns, fns...)
	return mms
}

// Scan applies the selector query and scans the result into the given value.
func (mms *MessageMailSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mms.ctx, "Select")
	if err := mms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MessageMailQuery, *MessageMailSelect](ctx, mms.MessageMailQuery, mms, mms.inters, v)
}

func (mms *MessageMailSelect) sqlScan(ctx context.Context, root *MessageMailQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mms.fns))
	for _, fn := range mms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
