// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CategoryMain is the predicate function for categorymain builders.
type CategoryMain func(*sql.Selector)

// CategorySub is the predicate function for categorysub builders.
type CategorySub func(*sql.Selector)

// ExecutionLog is the predicate function for executionlog builders.
type ExecutionLog func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// MessageMail is the predicate function for messagemail builders.
type MessageMail func(*sql.Selector)

// Script is the predicate function for script builders.
type Script func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
